# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aditya Kumar Akash
email: adityakumarakash@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the site of AKA !
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://adityakumarakash.github.io" # the base hostname & protocol for your site
twitter_username: adityakumarakash
github_username:  adityakumarakash

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal
